using Calcpad.Document.Core.Utils;

namespace Calcpad.WebApi.Controllers.DTOs
{
    public class UploadCalcpadRequestData
    {
        /// <summary>
        /// unique id for the file, can be generated by client
        /// this id should be stored in database to identify the file in client or other service
        /// </summary>
        public string UniqueId { get; set; }

        /// <summary>
        /// this file name is only for display, the real saved file name is generated by server
        /// provided by client
        /// </summary>
        public string FileName { get; set; }

        public IFormFile File { get; set; }

        /// <summary>
        /// true when the file is an calcpad file
        /// </summary>
        public bool IsCpdFile => CpdExtensions.Contains(Path.GetExtension(File.FileName).ToLower());

        /// <summary>
        /// save the file to server and return the file path
        /// </summary>
        /// <returns>uniqueId/fileName</returns>
        public string GetUniqueFileName()
        {
            return $"{UniqueId}/{GetFileName()}";
        }

        public string GetFileName()
        {
            if (!string.IsNullOrEmpty(FileName))
            {
                return FileName;
            }

            return File.FileName;
        }

        /// <summary>
        /// override the file at savedPath
        /// </summary>
        /// <param name="savedPath"></param>
        /// <returns></returns>
        public string Save(string savedPath)
        {
            var dir = Path.GetDirectoryName(savedPath);
            Directory.CreateDirectory(dir!);

            // save the file
            using (var stream = new FileStream(savedPath, FileMode.Create))
            {
                File.CopyTo(stream);
            }

            return savedPath;
        }

        private static string[] CpdExtensions => FileExtensionsList.CpdFileExtensions;

        // images、csv、excel、txt
        private static readonly List<string> _otherExtensions =
        [
            .. FileExtensionsList.ImageFileExtensions,
            .. FileExtensionsList.CsvFileExtensions,
            .. FileExtensionsList.ExcelFileExtensions,
        ];

        /// <summary>
        /// check if the file extension is valid
        /// support: .cpd, .cpdz, .txt
        /// images: .png, .jpg, .jpeg, .webp
        /// </summary>
        /// <returns></returns>
        public bool IsValidExtensions()
        {
            var extension = Path.GetExtension(File.FileName).ToLower();
            return CpdExtensions.Contains(extension) || _otherExtensions.Contains(extension);
        }
    }
}
