//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Wpf.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of line expected..
        /// </summary>
        public static string End_of_line_expected {
            get {
                return ResourceManager.GetString("End_of_line_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting input fields values..
        /// </summary>
        public static string Error_getting_input_fields_values {
            get {
                return ResourceManager.GetString("Error_getting_input_fields_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Error.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Exception details:
        ///
        ///&quot;{0}&quot;.
        /// </summary>
        public static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string File_not_found {
            get {
                return ResourceManager.GetString("File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid compiler directive..
        /// </summary>
        public static string Invalid_compiler_directive {
            get {
                return ResourceManager.GetString("Invalid_compiler_directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method..
        /// </summary>
        public static string Invalid_method {
            get {
                return ResourceManager.GetString("Invalid_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax..
        /// </summary>
        public static string Invalid_syntax {
            get {
                return ResourceManager.GetString("Invalid_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///There is no unsaved data. If the problem persists, please contact proektsoft.bg@gmail.com..
        /// </summary>
        public static string ReportUnhandledExceptionAndClose_NoUnsavedData {
            get {
                return ResourceManager.GetString("ReportUnhandledExceptionAndClose_NoUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Calcpad saved your work and tried to recover automatically..
        /// </summary>
        public static string ReportUnhandledExceptionAndClose_NoUnsavedData_RecoveryAttempted {
            get {
                return ResourceManager.GetString("ReportUnhandledExceptionAndClose_NoUnsavedData_RecoveryAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///There was unsaved data. Calcpad tried, but was unable to recover. If the problem persists, please contact proektsoft.bg@gmail.com..
        /// </summary>
        public static string ReportUnhandledExceptionAndClose_UnsavedData_RecoveryFailed {
            get {
                return ResourceManager.GetString("ReportUnhandledExceptionAndClose_UnsavedData_RecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single expression expected..
        /// </summary>
        public static string Single_expression_expected {
            get {
                return ResourceManager.GetString("Single_expression_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeclared function..
        /// </summary>
        public static string Undeclared_function {
            get {
                return ResourceManager.GetString("Undeclared_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeclared variable..
        /// </summary>
        public static string Undeclared_variable {
            get {
                return ResourceManager.GetString("Undeclared_variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined macro or parameter..
        /// </summary>
        public static string Undefined_macro_or_parameter {
            get {
                return ResourceManager.GetString("Undefined_macro_or_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined units..
        /// </summary>
        public static string Undefined_units {
            get {
                return ResourceManager.GetString("Undefined_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred in Calcpad: &quot;{0}&quot;
        ///
        ///Source: &quot;{1}&quot;.
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
    }
}
