//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Wpf.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value/magnitude.
        /// </summary>
        public static string AbsoluteValue {
            get {
                return ResourceManager.GetString("AbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        public static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate and Interpolation.
        /// </summary>
        public static string AggregateAndInterpolation {
            get {
                return ResourceManager.GetString("AggregateAndInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angle whose tangent is x/y.
        /// </summary>
        public static string AngleWhoseTangentIsXDividedByY {
            get {
                return ResourceManager.GetString("AngleWhoseTangentIsXDividedByY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of multiple values.
        /// </summary>
        public static string AverageOfMultipleValues {
            get {
                return ResourceManager.GetString("AverageOfMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avogadro constant.
        /// </summary>
        public static string AvogadroConstant {
            get {
                return ResourceManager.GetString("AvogadroConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Logarithm.
        /// </summary>
        public static string BinaryLogarithm {
            get {
                return ResourceManager.GetString("BinaryLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boltzmann constant.
        /// </summary>
        public static string BoltzmannConstant {
            get {
                return ResourceManager.GetString("BoltzmannConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        public static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional and Logical.
        /// </summary>
        public static string ConditionalAndLogical {
            get {
                return ResourceManager.GetString("ConditionalAndLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional evaluation.
        /// </summary>
        public static string ConditionalEvaluation_Function {
            get {
                return ResourceManager.GetString("ConditionalEvaluation_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string Constants_Header {
            get {
                return ResourceManager.GetString("Constants_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosecant.
        /// </summary>
        public static string Cosecant {
            get {
                return ResourceManager.GetString("Cosecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine.
        /// </summary>
        public static string Cosine {
            get {
                return ResourceManager.GetString("Cosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotangent.
        /// </summary>
        public static string Cotangent {
            get {
                return ResourceManager.GetString("Cotangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coulomb constant.
        /// </summary>
        public static string CoulombConstant {
            get {
                return ResourceManager.GetString("CoulombConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Root.
        /// </summary>
        public static string CubicRoot {
            get {
                return ResourceManager.GetString("CubicRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Logarithm.
        /// </summary>
        public static string DecimalLogarithm {
            get {
                return ResourceManager.GetString("DecimalLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Bar.
        /// </summary>
        public static string DivisionBar {
            get {
                return ResourceManager.GetString("DivisionBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth mass.
        /// </summary>
        public static string EarthMass {
            get {
                return ResourceManager.GetString("EarthMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron mass.
        /// </summary>
        public static string ElectronMass {
            get {
                return ResourceManager.GetString("ElectronMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary charge.
        /// </summary>
        public static string ElementaryCharge {
            get {
                return ResourceManager.GetString("ElementaryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal To.
        /// </summary>
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler constant.
        /// </summary>
        public static string EulerConstant {
            get {
                return ResourceManager.GetString("EulerConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler number.
        /// </summary>
        public static string EulerNumber {
            get {
                return ResourceManager.GetString("EulerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponentiation.
        /// </summary>
        public static string Exponentiation {
            get {
                return ResourceManager.GetString("Exponentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial.
        /// </summary>
        public static string Factorial {
            get {
                return ResourceManager.GetString("Factorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faraday constant.
        /// </summary>
        public static string FaradayConstant {
            get {
                return ResourceManager.GetString("FaradayConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric mean.
        /// </summary>
        public static string GeometricMean {
            get {
                return ResourceManager.GetString("GeometricMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden ratio.
        /// </summary>
        public static string GoldenRatio {
            get {
                return ResourceManager.GetString("GoldenRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational acceleration on Earth.
        /// </summary>
        public static string GravitationalAcceleration {
            get {
                return ResourceManager.GetString("GravitationalAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational constant.
        /// </summary>
        public static string GravitationalConstant {
            get {
                return ResourceManager.GetString("GravitationalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than or Equal.
        /// </summary>
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The greatest common divisor of two integers.
        /// </summary>
        public static string GreatestCommonDivisor {
            get {
                return ResourceManager.GetString("GreatestCommonDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermite spline interpolation.
        /// </summary>
        public static string HermiteSplineInterpolation {
            get {
                return ResourceManager.GetString("HermiteSplineInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic.
        /// </summary>
        public static string Hyperbolic {
            get {
                return ResourceManager.GetString("Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Cosecant.
        /// </summary>
        public static string HyperbolicCosecant {
            get {
                return ResourceManager.GetString("HyperbolicCosecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Cosine.
        /// </summary>
        public static string HyperbolicCosine {
            get {
                return ResourceManager.GetString("HyperbolicCosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Cotangent.
        /// </summary>
        public static string HyperbolicCotangent {
            get {
                return ResourceManager.GetString("HyperbolicCotangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Secant.
        /// </summary>
        public static string HyperbolicSecant {
            get {
                return ResourceManager.GetString("HyperbolicSecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Sine.
        /// </summary>
        public static string HyperbolicSine {
            get {
                return ResourceManager.GetString("HyperbolicSine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic Tangent.
        /// </summary>
        public static string HyperbolicTangent {
            get {
                return ResourceManager.GetString("HyperbolicTangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imaginary part of a complex number.
        /// </summary>
        public static string ImaginaryPartOfAComplexNumber {
            get {
                return ResourceManager.GetString("ImaginaryPartOfAComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer Division.
        /// </summary>
        public static string IntegerDivision {
            get {
                return ResourceManager.GetString("IntegerDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Cosecant.
        /// </summary>
        public static string InverseCosecant {
            get {
                return ResourceManager.GetString("InverseCosecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Cosine.
        /// </summary>
        public static string InverseCosine {
            get {
                return ResourceManager.GetString("InverseCosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Cotangent.
        /// </summary>
        public static string InverseCotangent {
            get {
                return ResourceManager.GetString("InverseCotangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic.
        /// </summary>
        public static string InverseHyperbolic {
            get {
                return ResourceManager.GetString("InverseHyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Cosecant.
        /// </summary>
        public static string InverseHyperbolicCosecant {
            get {
                return ResourceManager.GetString("InverseHyperbolicCosecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Cosine.
        /// </summary>
        public static string InverseHyperbolicCosine {
            get {
                return ResourceManager.GetString("InverseHyperbolicCosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Cotangent.
        /// </summary>
        public static string InverseHyperbolicCotangent {
            get {
                return ResourceManager.GetString("InverseHyperbolicCotangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Secant.
        /// </summary>
        public static string InverseHyperbolicSecant {
            get {
                return ResourceManager.GetString("InverseHyperbolicSecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Sine.
        /// </summary>
        public static string InverseHyperbolicSine {
            get {
                return ResourceManager.GetString("InverseHyperbolicSine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Hyperbolic Tangent.
        /// </summary>
        public static string InverseHyperbolicTangent {
            get {
                return ResourceManager.GetString("InverseHyperbolicTangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Secant.
        /// </summary>
        public static string InverseSecant {
            get {
                return ResourceManager.GetString("InverseSecant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Sine.
        /// </summary>
        public static string InverseSine {
            get {
                return ResourceManager.GetString("InverseSine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Tangent.
        /// </summary>
        public static string InverseTangent {
            get {
                return ResourceManager.GetString("InverseTangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Trigonometric.
        /// </summary>
        public static string InverseTrigonometric {
            get {
                return ResourceManager.GetString("InverseTrigonometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The least common multiple of two integers.
        /// </summary>
        public static string LeastCommonMultiple {
            get {
                return ResourceManager.GetString("LeastCommonMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than or Equal.
        /// </summary>
        public static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear interpolation.
        /// </summary>
        public static string LinearInterpolation {
            get {
                return ResourceManager.GetString("LinearInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic, Exponential and Roots.
        /// </summary>
        public static string LogarithmicExponentialAndRoots {
            get {
                return ResourceManager.GetString("LogarithmicExponentialAndRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical &amp;quot;And&amp;quot;.
        /// </summary>
        public static string LogicalAnd {
            get {
                return ResourceManager.GetString("LogicalAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical and.
        /// </summary>
        public static string LogicalAnd_Function {
            get {
                return ResourceManager.GetString("LogicalAnd_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical not.
        /// </summary>
        public static string LogicalNot_Function {
            get {
                return ResourceManager.GetString("LogicalNot_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical &amp;quot;Or&amp;quot;.
        /// </summary>
        public static string LogicalOr {
            get {
                return ResourceManager.GetString("LogicalOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical or.
        /// </summary>
        public static string LogicalOr_Function {
            get {
                return ResourceManager.GetString("LogicalOr_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical &amp;quot;Xor&amp;quot;.
        /// </summary>
        public static string LogicalXor {
            get {
                return ResourceManager.GetString("LogicalXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical xor.
        /// </summary>
        public static string LogicalXor_Function {
            get {
                return ResourceManager.GetString("LogicalXor_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of multiple values.
        /// </summary>
        public static string MaximumOfMultipleValues {
            get {
                return ResourceManager.GetString("MaximumOfMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum of multiple values.
        /// </summary>
        public static string MinimumOfMultipleValues {
            get {
                return ResourceManager.GetString("MinimumOfMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo (reminder).
        /// </summary>
        public static string Modulo {
            get {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modulo (reminder) of an integer division.
        /// </summary>
        public static string Modulo_Description {
            get {
                return ResourceManager.GetString("Modulo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molar gas constant .
        /// </summary>
        public static string MolarGasConstant {
            get {
                return ResourceManager.GetString("MolarGasConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        public static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Exponent.
        /// </summary>
        public static string NaturalExponent {
            get {
                return ResourceManager.GetString("NaturalExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Logarithm.
        /// </summary>
        public static string NaturalLogarithm {
            get {
                return ResourceManager.GetString("NaturalLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutron mass.
        /// </summary>
        public static string NeutronMass {
            get {
                return ResourceManager.GetString("NeutronMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Equal To.
        /// </summary>
        public static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n-th Root.
        /// </summary>
        public static string NthRoot {
            get {
                return ResourceManager.GetString("NthRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phase of a complex number.
        /// </summary>
        public static string PhaseOfAComplexNumber {
            get {
                return ResourceManager.GetString("PhaseOfAComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant π (pi).
        /// </summary>
        public static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi number.
        /// </summary>
        public static string PiNumber {
            get {
                return ResourceManager.GetString("PiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planck constant.
        /// </summary>
        public static string PlanckConstant {
            get {
                return ResourceManager.GetString("PlanckConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product of multiple values.
        /// </summary>
        public static string ProductOfMultipleValues {
            get {
                return ResourceManager.GetString("ProductOfMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proton mass.
        /// </summary>
        public static string ProtonMass {
            get {
                return ResourceManager.GetString("ProtonMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random number between 0 and x.
        /// </summary>
        public static string RandomNumber {
            get {
                return ResourceManager.GetString("RandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The real part of a complex number.
        /// </summary>
        public static string RealPartOfAComplexNumber {
            get {
                return ResourceManager.GetString("RealPartOfAComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding.
        /// </summary>
        public static string Rounding {
            get {
                return ResourceManager.GetString("Rounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round to the nearest integer.
        /// </summary>
        public static string RoundToNearestInteger {
            get {
                return ResourceManager.GetString("RoundToNearestInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round to the lower integer.
        /// </summary>
        public static string RoundToTheLowerInteger {
            get {
                return ResourceManager.GetString("RoundToTheLowerInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round towards zero.
        /// </summary>
        public static string RoundTowardsZero {
            get {
                return ResourceManager.GetString("RoundTowardsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round up to the greater integer.
        /// </summary>
        public static string RoundUpToTheGreaterInteger {
            get {
                return ResourceManager.GetString("RoundUpToTheGreaterInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secant.
        /// </summary>
        public static string Secant {
            get {
                return ResourceManager.GetString("Secant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selective evaluation.
        /// </summary>
        public static string SelectiveEvaluation_Function {
            get {
                return ResourceManager.GetString("SelectiveEvaluation_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign of a number.
        /// </summary>
        public static string SignOfANumber {
            get {
                return ResourceManager.GetString("SignOfANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        public static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar mass.
        /// </summary>
        public static string SolarMass {
            get {
                return ResourceManager.GetString("SolarMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of light in vacuum.
        /// </summary>
        public static string SpeedOfLight {
            get {
                return ResourceManager.GetString("SpeedOfLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Root.
        /// </summary>
        public static string SquareRoot {
            get {
                return ResourceManager.GetString("SquareRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root of sum of squares.
        /// </summary>
        public static string SquareRootOfSumOfSquares {
            get {
                return ResourceManager.GetString("SquareRootOfSumOfSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stefan–Boltzmann constant.
        /// </summary>
        public static string StefanBoltzmannConstant {
            get {
                return ResourceManager.GetString("StefanBoltzmannConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        public static string Subtraction {
            get {
                return ResourceManager.GetString("Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of multiple values.
        /// </summary>
        public static string SumOfMultipleValues {
            get {
                return ResourceManager.GetString("SumOfMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of squares.
        /// </summary>
        public static string SumOfSquares {
            get {
                return ResourceManager.GetString("SumOfSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the n-th element.
        /// </summary>
        public static string TakeTheNthElement {
            get {
                return ResourceManager.GetString("TakeTheNthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent.
        /// </summary>
        public static string Tangent {
            get {
                return ResourceManager.GetString("Tangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric.
        /// </summary>
        public static string Trigonometric {
            get {
                return ResourceManager.GetString("Trigonometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of aluminium.
        /// </summary>
        public static string UnitWeightOfAluminium {
            get {
                return ResourceManager.GetString("UnitWeightOfAluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of concrete.
        /// </summary>
        public static string UnitWeightOfConcrete {
            get {
                return ResourceManager.GetString("UnitWeightOfConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of glass.
        /// </summary>
        public static string UnitWeightOfGlass {
            get {
                return ResourceManager.GetString("UnitWeightOfGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of steel.
        /// </summary>
        public static string UnitWeightOfSteel {
            get {
                return ResourceManager.GetString("UnitWeightOfSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of water.
        /// </summary>
        public static string UnitWeightOfWater {
            get {
                return ResourceManager.GetString("UnitWeightOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum magnetic permeability.
        /// </summary>
        public static string VacuumPermeability {
            get {
                return ResourceManager.GetString("VacuumPermeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum electric permittivity.
        /// </summary>
        public static string VacuumPermitivity {
            get {
                return ResourceManager.GetString("VacuumPermitivity", resourceCulture);
            }
        }
    }
}
