//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Wpf.ConstantsResources", typeof(ConstantsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avogadro constant.
        /// </summary>
        public static string AvogadroConstant {
            get {
                return ResourceManager.GetString("AvogadroConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boltzmann constant.
        /// </summary>
        public static string BoltzmannConstant {
            get {
                return ResourceManager.GetString("BoltzmannConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string Constants_Header {
            get {
                return ResourceManager.GetString("Constants_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coulomb constant.
        /// </summary>
        public static string CoulombConstant {
            get {
                return ResourceManager.GetString("CoulombConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth mass.
        /// </summary>
        public static string EarthMass {
            get {
                return ResourceManager.GetString("EarthMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron mass.
        /// </summary>
        public static string ElectronMass {
            get {
                return ResourceManager.GetString("ElectronMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary charge.
        /// </summary>
        public static string ElementaryCharge {
            get {
                return ResourceManager.GetString("ElementaryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler constant.
        /// </summary>
        public static string EulerConstant {
            get {
                return ResourceManager.GetString("EulerConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler number.
        /// </summary>
        public static string EulerNumber {
            get {
                return ResourceManager.GetString("EulerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faraday constant.
        /// </summary>
        public static string FaradayConstant {
            get {
                return ResourceManager.GetString("FaradayConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden ratio.
        /// </summary>
        public static string GoldenRatio {
            get {
                return ResourceManager.GetString("GoldenRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational acceleration on Earth.
        /// </summary>
        public static string GravitationalAcceleration {
            get {
                return ResourceManager.GetString("GravitationalAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational constant.
        /// </summary>
        public static string GravitationalConstant {
            get {
                return ResourceManager.GetString("GravitationalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molar gas constant.
        /// </summary>
        public static string MolarGasConstant {
            get {
                return ResourceManager.GetString("MolarGasConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutron mass.
        /// </summary>
        public static string NeutronMass {
            get {
                return ResourceManager.GetString("NeutronMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant π (pi).
        /// </summary>
        public static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planck constant.
        /// </summary>
        public static string PlanckConstant {
            get {
                return ResourceManager.GetString("PlanckConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proton mass.
        /// </summary>
        public static string ProtonMass {
            get {
                return ResourceManager.GetString("ProtonMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar mass.
        /// </summary>
        public static string SolarMass {
            get {
                return ResourceManager.GetString("SolarMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of light in vacuum.
        /// </summary>
        public static string SpeedOfLight {
            get {
                return ResourceManager.GetString("SpeedOfLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stefan–Boltzmann constant.
        /// </summary>
        public static string StefanBoltzmannConstant {
            get {
                return ResourceManager.GetString("StefanBoltzmannConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of aluminium.
        /// </summary>
        public static string UnitWeightOfAluminium {
            get {
                return ResourceManager.GetString("UnitWeightOfAluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of concrete.
        /// </summary>
        public static string UnitWeightOfConcrete {
            get {
                return ResourceManager.GetString("UnitWeightOfConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of glass.
        /// </summary>
        public static string UnitWeightOfGlass {
            get {
                return ResourceManager.GetString("UnitWeightOfGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of steel.
        /// </summary>
        public static string UnitWeightOfSteel {
            get {
                return ResourceManager.GetString("UnitWeightOfSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit weight of water.
        /// </summary>
        public static string UnitWeightOfWater {
            get {
                return ResourceManager.GetString("UnitWeightOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum magnetic permeability.
        /// </summary>
        public static string VacuumPermeability {
            get {
                return ResourceManager.GetString("VacuumPermeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum electric permittivity.
        /// </summary>
        public static string VacuumPermitivity {
            get {
                return ResourceManager.GetString("VacuumPermitivity", resourceCulture);
            }
        }
    }
}
