//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Wpf.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlock the source code for editing?.
        /// </summary>
        public static string Are_you_sure_you_want_to_unlock_the_source_code_for_editing {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_unlock_the_source_code_for_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://calcpad.eu/download/help.html.
        /// </summary>
        public static string calcpad_download_help_html {
            get {
                return ResourceManager.GetString("calcpad_download_help_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcpad Worksheet (*.cpd)|*.cpd|Calcpad Compiled (*.cpdz)|*.cpdz|Text File (*.txt)|*.txt.
        /// </summary>
        public static string Command_Open_Calcpad_Worksheet {
            get {
                return ResourceManager.GetString("Command_Open_Calcpad_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt|Calcpad Worksheet (*.cpd)|*.cpd|Calcpad Compiled (*.cpdz)|*.cpdz.
        /// </summary>
        public static string Command_Open_Text_File {
            get {
                return ResourceManager.GetString("Command_Open_Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile to input form (F4).
        /// </summary>
        public static string Compile_to_input_form_F4 {
            get {
                return ResourceManager.GetString("Compile_to_input_form_F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting docx file. Display validation log?.
        /// </summary>
        public static string Error_Exporting_Docx_File {
            get {
                return ResourceManager.GetString("Error_Exporting_Docx_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting units..
        /// </summary>
        public static string Error_getting_units {
            get {
                return ResourceManager.GetString("Error_getting_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Invalid number. Please correct and then try again..
        /// </summary>
        public static string Error_Invalid_number_Please_correct_and_then_try_again {
            get {
                return ResourceManager.GetString("Error_Invalid_number_Please_correct_and_then_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting units..
        /// </summary>
        public static string Error_setting_units {
            get {
                return ResourceManager.GetString("Error_setting_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcpad Compiled (*.cpdz)|*.cpdz.
        /// </summary>
        public static string FileSaveAs_Calcpad_Compiled {
            get {
                return ResourceManager.GetString("FileSaveAs_Calcpad_Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;errorHeader&quot;&gt;Found &lt;b&gt;{0}&lt;/b&gt; errors in modules and macros:.
        /// </summary>
        public static string Found_Errors_In_Modules_And_Macros {
            get {
                return ResourceManager.GetString("Found_Errors_In_Modules_And_Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop! Inline Html elements must not cross text lines..
        /// </summary>
        public static string Inline_Html_elements_must_not_cross_text_lines {
            get {
                return ResourceManager.GetString("Inline_Html_elements_must_not_cross_text_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source code for editing (F4).
        /// </summary>
        public static string Open_source_code_for_editing__F4 {
            get {
                return ResourceManager.GetString("Open_source_code_for_editing__F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not saved. Save?.
        /// </summary>
        public static string SavePrompt {
            get {
                return ResourceManager.GetString("SavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery failed with error:
        ///&quot;{0}&quot;.
        ///You can find your unsaved data in
        ///&quot;{1}&quot;..
        /// </summary>
        public static string TryRestoreState_Failed {
            get {
                return ResourceManager.GetString("TryRestoreState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcpad recovered from unexpected shutdown.
        ///Would you like to restore your unsaved data?.
        /// </summary>
        public static string TryRestoreState_Recovered_SavePrompt {
            get {
                return ResourceManager.GetString("TryRestoreState_Recovered_SavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwarped code.
        /// </summary>
        public static string Unwarped_code {
            get {
                return ResourceManager.GetString("Unwarped_code", resourceCulture);
            }
        }
    }
}
