using Calcpad.WebApi.Models.Base;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json.Linq;

namespace Calcpad.WebApi.Models
{
    public class CalcpadLangModel : MongoDoc
    {
        /// <summary>
        /// Cpd file human unique id
        /// One unique Id may owns by multiple calcpad file
        /// You can use uniqueId as calcpad file template identifier
        /// </summary>
        public string UniqueId { get; set; }

        public string Key { get; set; }

        /// <summary>
        /// Cpd file version
        /// </summary>
        public int Version { get; set; }

        /// <summary>
        /// Language code, e.g. "en", "fr"
        /// </summary>
        public string Lang { get; set; }

        /// <summary>
        /// Language value
        /// </summary>
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the content was generated by artificial intelligence.
        /// If false, the content was provided by a human, AI will not override it.
        /// </summary>
        public bool IsByAI { get; set; } = true;

        [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
        public DateTime LastModifyDate { get; set; } = DateTime.UtcNow;
    }
}
