//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Cli.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Copyright: © 2024 by Proektsoft EOOD..
        /// </summary>
        internal static string Copyright_2023_By_Proektsoft_EOOD {
            get {
                return ResourceManager.GetString("Copyright_2023_By_Proektsoft_EOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter math expressions or commands (or type HELP for further instructions).
        /// </summary>
        internal static string Enter_Math_Expressions_Or_Commands_Or_Type_HELP_For_Further_Instructions {
            get {
                return ResourceManager.GetString("Enter_Math_Expressions_Or_Commands_Or_Type_HELP_For_Further_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the settings file....
        /// </summary>
        internal static string Loading_The_Settings_File {
            get {
                return ResourceManager.GetString("Loading_The_Settings_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key when ready..
        /// </summary>
        internal static string Press_Any_Key_When_Ready {
            get {
                return ResourceManager.GetString("Press_Any_Key_When_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue..
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem \&quot;{0}\&quot; does not exist..
        /// </summary>
        internal static string Problem_0_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Problem_0_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem title:.
        /// </summary>
        internal static string Problem_Title {
            get {
                return ResourceManager.GetString("Problem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no saved problems..
        /// </summary>
        internal static string There_Are_No_Saved_Problems {
            get {
                return ResourceManager.GetString("There_Are_No_Saved_Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Welcome to Calcpad VM command line interpreter v.{0}.{1}.{2}!.
        /// </summary>
        internal static string Welcome_To_Calcpad_Command_Line_Interpreter {
            get {
                return ResourceManager.GetString("Welcome_To_Calcpad_Command_Line_Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to restore the previous settings (y/n)?.
        /// </summary>
        internal static string WouldYouLikeToRestoreThePreviousSettingsYN {
            get {
                return ResourceManager.GetString("WouldYouLikeToRestoreThePreviousSettingsYN", resourceCulture);
            }
        }
    }
}
