using Calcpad.Document.Archive;
using Calcpad.Document.Core.Segments;
using Calcpad.WebApi.Configs;
using Calcpad.WebApi.Models;
using Calcpad.WebApi.Models.Base;
using Calcpad.WebApi.Utils.Web.Exceptions;
using Calcpad.WebApi.Utils.Web.Service;
using HtmlAgilityPack;
using MongoDB.Driver.Linq;
using System.Text;

namespace Calcpad.WebApi.Services.Calcpad
{
    /// <summary>
    /// calcpad file content service
    /// </summary>
    /// <param name="db"></param>
    /// <param name="storageConfig"></param>
    public class CpdContentService(
        MongoDBContext db,
        AppSettings<StorageConfig> storageConfig,
        CycleDetectorService cycleDetector
    ) : IScopedService
    {
        /// <summary>
        /// operations:
        /// 1. set meta info to file head
        /// 2. resolve include path to server path
        /// 3. resolve read from path to server path
        /// resolve include path to server path
        /// </summary>
        /// <param name="fullPath"></param>
        /// <param name="cpdUid"></param>
        /// <returns></returns>
        public async Task<List<string>> SetMeataInfoAndResolvePath(
            string fullPath,
            string cpdUid
        )
        {
            var cpdReader = CpdReaderFactory.CreateCpdReader(fullPath);
            var includes = cpdReader.ReadIncludeLines();

            var includesQueue = new Queue<IncludeLine>();
            if (includes.Count > 0)
            {
                // replace include path to server path
                var uIds = includes.Select(x => x.Uid).ToList();

                // find all include files
                var cpdObjects = await db.AsQueryable<CalcpadFileModel>()
                    .Where(x => uIds.Contains(x.UniqueId))
                    .ToListAsync();

                // replace uid to service path
                foreach (var include in includes.OrderBy(x => x.RowIndex))
                {
                    var includeFile = cpdObjects.FirstOrDefault(x => x.UniqueId == include.Uid);
                    if (includeFile != null)
                    {
                        include.AddUid(includeFile.UniqueId);
                        include.SetFilePath(includeFile.FullName);
                        includesQueue.Enqueue(include);
                    }
                }
            }

            // add header, example:
            // #local '<meta>
            // #hide
            // 'id:1
            // 'description: this is auto generated by calcpad web api, do not edit it
            // #show
            // #global '</meta>
            var header = new List<string>
            {
                "#local '<meta>",
                "#hide",
                "'uid:" + cpdUid,
                "'description: this is auto generated by calcpad web api, do not edit it",
                "#show",
                "#global '</meta>",
            };
            var headerInfo = string.Join(Environment.NewLine, header) + Environment.NewLine;
            var content = cpdReader.ReadAllText();
            if (includesQueue.Count > 0)
            {
                var sb = new StringBuilder(
                    cpdReader.ReadAllText().Length + headerInfo.Length + includes.Count * 40
                );

                var index = -1;
                var currentInclude = includesQueue.Dequeue();
                foreach (var line in cpdReader.ReadStringLines())
                {
                    index++;
                    if (currentInclude != null && index == currentInclude.RowIndex)
                    {
                        sb.AppendLine(currentInclude.ToString());
                        if (includesQueue.Count > 0)
                        {
                            currentInclude = includesQueue.Dequeue();
                        }
                        else
                        {
                            currentInclude = null;
                        }
                        continue;
                    }

                    sb.AppendLine(line);
                }
                content = sb.ToString();
            }

            // upsert meta info at head
            const string startMarker = "#local '<meta>";
            const string endMarker = "#global '</meta>";
            var startIndex = content.IndexOf(startMarker, StringComparison.OrdinalIgnoreCase);
            if (startIndex >= 0)
            {
                var endIndex = content.IndexOf(
                    endMarker,
                    startIndex,
                    StringComparison.OrdinalIgnoreCase
                );
                if (endIndex >= 0)
                {
                    // remove old meta info
                    content = content.Remove(startIndex, endIndex + endMarker.Length - startIndex);
                }
                else
                {
                    content = content.Remove(startIndex, 1);
                }
            }

            var fileWriter = CpdWriterFactory.CreateCpdWriter();
            fileWriter.WriteFile(fullPath, headerInfo + content);

            // check cycles
            var includeIds = includes
                .Select(x => x.Uid)
                .Where(x => !string.IsNullOrEmpty(x))
                .ToList();
            var hasCycle = await cycleDetector.HasCycleAsync(cpdUid, includeIds);
            if (hasCycle)
            {
                throw new KnownException("include cycle detected");
            }

            return includeIds;
        }

        /// <summary>
        /// get file access uri
        /// if public file, return public stream uri
        /// if private file, return service path with uid
        /// </summary>
        /// <param name="fileObject"></param>
        /// <returns></returns>
        public string GetFileAccessUri(CalcpadFileModel fileObject)
        {
            if (fileObject.IsPublic)
            {
                return $"api/v1/calcpad-file/stream/public/{fileObject.Id}?uid={fileObject.UniqueId}";
            }

            return $"{fileObject.FullName}'?uid={fileObject.UniqueId}";
        }

        /// <summary>
        /// simplify html, remain row or p element which contains input,select,h1-h6
        /// </summary>
        /// <param name="originHtml"></param>
        /// <returns></returns>
        public string SimplifyHtml(string originHtml)
        {
            if (string.IsNullOrEmpty(originHtml))
            {
                return string.Empty;
            }

            var doc = new HtmlDocument();
            doc.LoadHtml(originHtml);

            // retain only nodes that should be kept
            var nodesToKeep = new List<HtmlNode>();
            foreach (var node in doc.DocumentNode.ChildNodes)
            {
                if (ShouldRetainNode(node))
                    nodesToKeep.Add(node);
            }

            // create new document with only the nodes to keep
            var newDoc = new HtmlDocument();
            foreach (var node in nodesToKeep)
            {
                newDoc.DocumentNode.AppendChild(node.Clone());
            }

            if (newDoc.DocumentNode.ChildNodes.Count == 0)
            {
                return originHtml;
            }
            return newDoc.DocumentNode.OuterHtml;
        }

        /// <summary>
        /// check if node should be retained
        /// </summary>
        /// <param name="node"></param>
        /// <returns></returns>
        private static bool ShouldRetainNode(HtmlNode node)
        {
            if (node.NodeType != HtmlNodeType.Element)
                return false;

            var tag = node.Name.ToLower();
            if (tag.StartsWith('h'))
                return true;

            if (tag.StartsWith("img"))
                return true;

            // retain p element which contains input or select
            if (tag == "p" && ContainsInputOrSelect(node))
                return true;

            return false;
        }

        private static HashSet<string> _supportTags = ["input", "select"];

        /// <summary>
        /// check if node or its children contains input or select element
        /// </summary>
        /// <param name="node"></param>
        /// <returns></returns>
        private static bool ContainsInputOrSelect(HtmlNode node)
        {
            if (_supportTags.Contains(node.Name.ToLower()))
            {
                return true;
            }

            foreach (var child in node.ChildNodes)
            {
                if (ContainsInputOrSelect(child))
                {
                    return true;
                }
            }
            return false;
        }
    }
}
