using Calcpad.Document;
using Calcpad.Document.Archive;
using Calcpad.Document.Core.Segments;
using Calcpad.Document.Core.Utils;
using Calcpad.WebApi.Configs;
using Calcpad.WebApi.Models;
using Calcpad.WebApi.Models.Base;
using Calcpad.WebApi.Utils.Encrypt;
using Calcpad.WebApi.Utils.Files;
using Calcpad.WebApi.Utils.Web.Service;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Driver.Linq;

namespace Calcpad.WebApi.Services.Calcpad
{
    /// <summary>
    /// calcpad file helper service
    /// </summary>
    /// <param name="db"></param>
    /// <param name="storageConfig"></param>
    public class CpdStorageService(
        MongoDBContext db,
        AppSettings<StorageConfig> storageConfig,
        AppSettings<AppConfig> appConfig
    ) : ISingletonService
    {
        /// <summary>
        /// get a saved path relative to storage root
        /// </summary>
        /// <param name="bucketName"></param>
        /// <param name="fileName"></param>
        /// <returns>StoragetRoot/bucketName/yyyy/mm/dd/fileName</returns>
        public string GetObjectName(string bucketName, string fileName)
        {
            var savedPath = Path.Combine(
                storageConfig.Value.Root,
                bucketName,
                DateTime.UtcNow.ToString("yyyy/MM/dd"),
                fileName
            );
            var dir = Path.GetDirectoryName(savedPath);
            Directory.CreateDirectory(dir!);
            return Path.GetRelativePath(storageConfig.Value.Root, savedPath).Replace('\\', '/');
        }

        /// <summary>
        /// get calcpad file file path, storageroot/calcpad-files
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public string GetCpdObjectName(string fileName)
        {
            var ext = Path.GetExtension(fileName);
            return GetObjectName(
                FileExtensionsList.CpdFileExtensions.Contains(ext) ? "calcpad-files" : "public",
                fileName
            );
        }

        /// <summary>
        /// Get full path from relative path which generated by <see cref="GetCpdObjectName"/>
        /// </summary>
        /// <param name="objectName"></param>
        /// <returns></returns>
        public string GetCpdAbsoluteFullName(string objectName)
        {
            var path = $"%{storageConfig.Value.Environment}%/{objectName}";
            return Environment.ExpandEnvironmentVariables(path);
        }

        /// <summary>
        /// get a public resource dir for calcpad
        /// </summary>
        /// <param name="cpdPath"></param>
        /// <returns></returns>
        public string GetCpdPublicResourceDir(string cpdPath)
        {
            var fullPath = GetFullPath(cpdPath);
            return Path.Combine(storageConfig.Value.Root, "public/cpd-resources", fullPath.ToMD5())
                .Replace('\\', '/');
        }

        /// <summary>
        /// Generate a read path for calcpad #read
        /// format: public/cpd-resources/md5(cpdFileFullPath)/filename
        /// </summary>
        /// <param name="cpdFullPath">for generate container dir by md5 valuem</param>
        /// <param name="readFromPath"></param>
        /// <returns>read path</returns>
        public string GetReadFromPath(string cpdFullPath, string readFromPath)
        {
            var resourceDir = GetCpdPublicResourceDir(cpdFullPath);
            var publicPath = Path.Combine(resourceDir, Path.GetFileName(readFromPath));
            // create directory
            Directory.CreateDirectory(Path.GetDirectoryName(publicPath)!);
            return publicPath.Replace('\\', '/');
        }

        /// <summary>
        /// get full path by file path, expand environment variables
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        public string GetFullPath(string filePath)
        {
            var path = Path.GetFullPath(Environment.ExpandEnvironmentVariables(filePath));
            return path;
        }

        /// <summary>
        /// get a path relative to storage root
        /// </summary>
        /// <param name="fullPath"></param>
        /// <returns></returns>
        public string GetRelativePathToStorageRoot(string fullPath)
        {
            var relativeTo = Path.GetFullPath(storageConfig.Value.Root);
            return Path.GetRelativePath(relativeTo, fullPath).Replace('\\', '/');
        }

        /// <summary>
        /// get a path relative to current directory
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        public string GetRelativePathToCurrentDir(string filePath)
        {
            var relativeTo = Path.GetFullPath(Environment.CurrentDirectory);
            var fullPath = GetFullPath(filePath);
            return Path.GetRelativePath(relativeTo, fullPath).Replace('\\', '/');
        }

        /// <summary>
        /// zip cpd file
        /// </summary>
        /// <param name="uniqueId"></param>
        /// <returns></returns>
        public async Task<(Stream?, string)> ZipAndDownloadCpdFile(string uniqueId)
        {
            var cpdModel = await db.AsQueryable<CalcpadFileModel>()
                .Where(x => x.UniqueId == uniqueId && x.IsCpd)
                .FirstOrDefaultAsync();
            if (cpdModel == null)
                return (null, string.Empty);
            var fullPath = GetCpdAbsoluteFullName(cpdModel.ObjectName);
            if (!File.Exists(fullPath))
                return (null, string.Empty);

            // create zip
            // create template dir
            var rootDir = Path.Combine(storageConfig.Value.Root, "temp/cpdzip", cpdModel.UniqueId);
            Directory.CreateDirectory(rootDir);

            // copy file and resources
            await CopyCpdFileAndResources(rootDir, cpdModel, true);

            var zipFilePath = Path.Combine(
                storageConfig.Value.Root,
                "temp/cpdzip",
                $"{cpdModel.UniqueId}_{Path.GetFileNameWithoutExtension(cpdModel.FileName)}.zip"
            );
            await ZipDirectory(rootDir, zipFilePath);

            return (
                new ReadAndDeleteStream(zipFilePath),
                Path.GetFileName(zipFilePath).Split("_").Last()
            );
        }

        /// <summary>
        /// copy a cpd file to target dir
        /// and its includes、excels、images to resources sub dir
        /// </summary>
        /// <param name="rootDir"></param>
        /// <param name="cpdModel"></param>
        /// <param name="isMain"></param>
        /// <returns></returns>
        private async Task CopyCpdFileAndResources(
            string rootDir,
            CalcpadFileModel cpdModel,
            bool isMain
        )
        {
            // copy main file to rootDir
            var fullPath = GetCpdAbsoluteFullName(cpdModel.ObjectName);

            var targetPath = Path.Combine(
                rootDir,
                isMain ? cpdModel.FileName : $"{cpdModel.UniqueId}_{cpdModel.FileName}"
            );

            // copy cpd file to target path
            var reader = CpdReaderFactory.CreateCpdReader(fullPath);

            // image is web path, so no need to copy

            // copy read data
            var readLines = reader.GetReadLines();
            var readsPath = Path.Combine(fullPath, "reads");
            if (readLines.Count > 0)
                Directory.CreateDirectory(readsPath);
            foreach (var readLine in readLines)
            {
                var fullDataPath = Path.GetFullPath(readLine.FilePath);
                if (File.Exists(fullDataPath))
                {
                    var dataFileName = Path.GetFileName(fullDataPath);
                    var targetDataPath = Path.Combine(readsPath, Path.GetFileName(dataFileName));
                    File.Copy(fullDataPath, targetDataPath, true);
                    // modify read line path
                    readLine.SetFilePath($"./reads/{dataFileName}");
                }
            }

            // save modified read lines
            var includeLines = reader.GetIncludeLines();
            var includesDir = Path.Combine(rootDir, "includes");
            if (includeLines.Count > 0)
                Directory.CreateDirectory(includesDir);
            foreach (var includeLine in includeLines)
            {
                if (includeLine.Uid.IsNullOrEmpty())
                    continue;

                var includeModel = await db.AsQueryable<CalcpadFileModel>()
                    .Where(x => x.UniqueId == includeLine.Uid)
                    .FirstOrDefaultAsync();
                if (includeModel != null)
                    continue;

                await CopyCpdFileAndResources(includesDir, includeModel, false);
                includeLine.SetFilePath($"./includes/{cpdModel.UniqueId}_{cpdModel.FileName}");
            }

            // 更新主文件并保存
            var allLines = new List<CpdLine>();
            allLines.AddRange(readLines);
            allLines.AddRange(includeLines);

            var content = CpdWriter.BuildCpdContent(reader.ReadStringLines(), allLines);
            var cpdWriter = CpdWriterFactory.CreateCpdWriter();
            cpdWriter.WriteFile(targetPath, content);
        }

        private static async Task ZipDirectory(string sourceDir, string zipFilePath)
        {
            if (File.Exists(zipFilePath))
                File.Delete(zipFilePath);
            await Task.Run(
                () => System.IO.Compression.ZipFile.CreateFromDirectory(sourceDir, zipFilePath)
            );
            // remove temp dir
            Directory.Delete(sourceDir, true);
        }

        /// <summary>
        /// get a web url by sub path
        /// </summary>
        /// <param name="subPath"></param>
        /// <returns></returns>
        public string GetWebUrl(string subPath)
        {
            return $"{appConfig.Value.BaseUrl}/{subPath.TrimStart('/')}";
        }

        /// <summary>
        /// get default file path by file extension
        /// </summary>
        /// <param name="fileExtension"></param>
        /// <returns></returns>
        public string GetDefaultFilePath(string fileExtension)
        {
            var extension = fileExtension.ToLower();
            // cpd、csv、excel
            if (FileExtensionsList.CpdFileExtensions.Contains(extension))
                return $"{storageConfig.Value.Root}/defaults/files/default_cpd.txt";

            if (FileExtensionsList.CsvFileExtensions.Contains(extension))
                return $"{storageConfig.Value.Root}/defaults/files/default_csv.csv";

            if (FileExtensionsList.ExcelFileExtensions.Contains(extension))
                return $"{storageConfig.Value.Root}/defaults/files/default_excel.xlsx";

            return string.Empty;
        }
    }
}
