//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcpad.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calcpad.Core.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate &quot;{0}&quot; as {1}..
        /// </summary>
        internal static string Cannot_evaluate__0__as__1__ {
            get {
                return ResourceManager.GetString("Cannot_evaluate__0__as__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate the function %F for %V = {0}..
        /// </summary>
        internal static string Cannot_evaluate_the_function_F_for_v__0__ {
            get {
                return ResourceManager.GetString("Cannot_evaluate_the_function_F_for_v__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete expression..
        /// </summary>
        internal static string Incomplete_expression {
            get {
                return ResourceManager.GetString("Incomplete_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent units: &quot;{0}&quot; and &quot;{1}&quot;..
        /// </summary>
        internal static string Inconsistent_units__0__and__1__ {
            get {
                return ResourceManager.GetString("Inconsistent_units__0__and__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator: &quot;{0}&quot;..
        /// </summary>
        internal static string Invalid_operator__0__ {
            get {
                return ResourceManager.GetString("Invalid_operator__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid symbol: &quot;{0}&quot;..
        /// </summary>
        internal static string Invalid_symbol__0__ {
            get {
                return ResourceManager.GetString("Invalid_symbol__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax: &quot;{0}&quot;..
        /// </summary>
        internal static string Invalid_syntax__0__ {
            get {
                return ResourceManager.GetString("Invalid_syntax__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid units: &quot;{0}&quot;..
        /// </summary>
        internal static string Invalid_units__0__ {
            get {
                return ResourceManager.GetString("Invalid_units__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid units for function: &quot;{0}({1})&quot;..
        /// </summary>
        internal static string Invalid_units_for_function__0_____1___ {
            get {
                return ResourceManager.GetString("Invalid_units_for_function__0__(__1__)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits out of range: [{0}; {1}]..
        /// </summary>
        internal static string Limits_out_of_range____0_____1___ {
            get {
                return ResourceManager.GetString("Limits_out_of_range_[__0__;__1__]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing left bracket &quot;(&quot;..
        /// </summary>
        internal static string Missing_left_bracket {
            get {
                return ResourceManager.GetString("Missing_left_bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing right bracket &quot;)&quot;..
        /// </summary>
        internal static string Missing_right_bracket {
            get {
                return ResourceManager.GetString("Missing_right_bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power must be unitless..
        /// </summary>
        internal static string Power_must_be_unitless {
            get {
                return ResourceManager.GetString("Power_must_be_unitless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root index cannot be complex number..
        /// </summary>
        internal static string Root_index_cannot_be_complex_number_ {
            get {
                return ResourceManager.GetString("Root_index_cannot_be_complex_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root index must be unitless..
        /// </summary>
        internal static string Root_index_must_be_unitless {
            get {
                return ResourceManager.GetString("Root_index_must_be_unitless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression on the right does not evaluate to units..
        /// </summary>
        internal static string The_expression_on_the_right_does_not_evaluate_to_units {
            get {
                return ResourceManager.GetString("The_expression_on_the_right_does_not_evaluate_to_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function %F is not defined for %V = {0}..
        /// </summary>
        internal static string The_function_F_is_not_defined_for_V__0__ {
            get {
                return ResourceManager.GetString("The_function_F_is_not_defined_for_V__0__", resourceCulture);
            }
        }
    }
}
